:Author: Raka
:Date: 19/12/2024
:Revision: version#
:License: Public Domain

= Project: Smart Home


== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Smart_Home_dec19a                => Arduino sketch folder
  ├── Smart_Home_dec19a.ino       => main Arduino file
  ├── SmartHome_Arduino-IoT-Cloud_diagram_sketch.png      => (optional) an image of the required schematics
  └── ReadMe.adoc                 => this file
....

=== License
This project is released under a MIT License.


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
