/* 
  Sketch generated by the Arduino IoT Cloud Thing "Smart Home"
  https://create.arduino.cc/cloud/things/26b010c0-6807-438b-ada5-9a322a21ac14 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch lampu;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "arduino_secrets.h"
#include "thingProperties.h"

int ledPin = D0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  pinMode(ledPin, OUTPUT);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}


/*
  Since Lampu is READ_WRITE variable, onLampuChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLampuChange()  {
  // Add your code here to act upon Lampu change
  if(lampu)
  {
    digitalWrite(ledPin,HIGH);
    Serial.println("ON");
  }
  else
  {
    digitalWrite(ledPin,LOW);
    Serial.println("OFF");
  }
}
