// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include <ArduinoMqttClient.h>

const char THING_ID[]           = "";
const char DEVICE_LOGIN_NAME[]  = "";

const char SSID[]               = "";    // Network SSID (name)
const char PASS[]               = "";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = "";    // Secret device password

void onLampuChange();

CloudSwitch lampu;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lampu, READWRITE, ON_CHANGE, onLampuChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
